
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Nov 14 00:29:17 ART 2010
//----------------------------------------------------

package rlwcompiler2010;

/** CUP generated class containing symbol constants. */
public class Symbols {
  /* terminals */
  public static final int TIMES = 17;
  public static final int SEMICOLON = 16;
  public static final int ELSE = 7;
  public static final int PLUS = 13;
  public static final int CONSTANT = 6;
  public static final int RCURLY = 15;
  public static final int IDENTIFIER = 8;
  public static final int IF = 9;
  public static final int LBRACKET = 10;
  public static final int COMPARATOR = 5;
  public static final int RBRACKET = 14;
  public static final int LCURLY = 11;
  public static final int TYPE = 18;
  public static final int COMMA = 4;
  public static final int EOF = 0;
  public static final int BY = 3;
  public static final int ASSIGNMENTSYMBOL = 2;
  public static final int MINUS = 12;
  public static final int PRINT = 19;
  public static final int error = 1;
  public static final int FOR = 20;
}

